### ISSUE TITLE
Can not install Rclusterpp

### ISSUE THREAD

**Issue by msuffiot** [nolanlab/citrus#122]
Dear all,

I tried to install 

`install_github("nolanlab/Rclusterpp")`
and get:
`Downloading GitHub repo nolanlab/Rclusterpp@master
from URL https://api.github.com/repos/nolanlab/Rclusterpp/zipball/master
Installing Rclusterpp
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/nn/kbdbvshj2ms0jq1dw58lthqwpp9dng/T/RtmprDw0OI/devtools49a8744c437e/nolanlab-Rclusterpp-740cb0b'  \
  --library='/Users/msuffiot/Library/R/3.5/library' --install-tests 

* installing *source* package ‘Rclusterpp’ ...
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/msuffiot/Library/R/3.5/library/Rcpp/include" -I"/Users/msuffiot/Library/R/3.5/library/RcppEigen/include" -I/usr/local/include  -I../inst/include -fopenmp -fPIC  -Wall -g -O2  -c hclust.cpp -o hclust.o
clang: error: unsupported option '-fopenmp'
make: *** [hclust.o] Error 1
ERROR: compilation failed for package ‘Rclusterpp’
* removing ‘/Users/msuffiot/Library/R/3.5/library/Rclusterpp’
Installation failed: Command failed (1)`

This is my sessionInfo():

`R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] brew_1.0-6           shiny_1.1.0          samr_2.0            
 [4] matrixStats_0.53.1   impute_1.54.0        flowCore_1.46.1     
 [7] BiocInstaller_1.30.0 ggplot2_2.2.1        pamr_1.55           
[10] survival_2.41-3      cluster_2.0.7-1      glmnet_2.0-16       
[13] foreach_1.4.4        Matrix_1.2-14        devtools_1.13.5     

loaded via a namespace (and not attached):
 [1] pcaPP_1.9-73        Rcpp_0.12.17        later_0.7.3        
 [4] DEoptimR_1.0-8      compiler_3.5.0      pillar_1.2.3       
 [7] git2r_0.21.0        plyr_1.8.4          iterators_1.0.9    
[10] tools_3.5.0         digest_0.6.15       jsonlite_1.5       
[13] memoise_1.1.0       tibble_1.4.2        gtable_0.2.0       
[16] lattice_0.20-35     rlang_0.2.1         graph_1.58.0       
[19] curl_3.2            parallel_3.5.0      mvtnorm_1.0-8      
[22] withr_2.1.2         httr_1.3.1          stats4_3.5.0       
[25] grid_3.5.0          robustbase_0.93-0   Biobase_2.40.0     
[28] rrcov_1.4-4         R6_2.2.2            tcltk_3.5.0        
[31] magrittr_1.5        corpcor_1.6.9       promises_1.0.1     
[34] htmltools_0.3.6     scales_0.5.0        codetools_0.2-15   
[37] splines_3.5.0       BiocGenerics_0.26.0 xtable_1.8-2       
[40] mime_0.5            colorspace_1.3-2    httpuv_1.4.3       
[43] lazyeval_0.2.1      munsell_0.5.0   `

Could someone help me please?
Thank you very much in advance.

best,
Madeleine

**Comment by DenisSch** [comment]
Similar problem here

```
Installing package into ‘/Users/denis/Library/R/3.5/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘Rclusterpp’ ...
** libs
/opt/local/bin/g++-mp-4.8 -arch x86_64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/denis/Library/R/3.5/library/Rcpp/include" -I"/Users/denis/Library/R/3.5/library/RcppEigen/include" -I/usr/local/include  -I../inst/include -fopenmp -fPIC  -Wall -g -O2  -c hclust.cpp -o hclust.o
In file included from /opt/local/include/gcc48/c++/bits/postypes.h:40:0,
                 from /opt/local/include/gcc48/c++/bits/char_traits.h:40,
                 from /opt/local/include/gcc48/c++/string:40,
                 from /opt/local/include/gcc48/c++/stdexcept:39,
                 from hclust.cpp:1:
/opt/local/include/gcc48/c++/cwchar:44:19: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
                   ^
compilation terminated.
make: *** [hclust.o] Error 1
ERROR: compilation failed for package ‘Rclusterpp’
* removing ‘/Users/denis/Library/R/3.5/library/Rclusterpp’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/t0/mdwkshy515dfbqj16t30h9v00000gr/T//RtmpzMvqCK/file382f1723add/Rclusterpp_0.2.4.tar.gz’ had non-zero exit status
```

**Comment by SamGG** [comment]
Hi, I don't have a Mac. I will only point a few clues:
* start by installing Rclusterpp alone
* report error to Rclsuterpp repository https://github.com/nolanlab/Rclusterpp
* check https://github.com/nolanlab/Rclusterpp/wiki/Getting-Started
* check this [french installation notice](https://github.com/nolanlab/Rclusterpp) in case it could help ("Installation sous Mac" paragraph).

Best.

**Comment by DenisSch** [comment]
I have big troubles installing citrus also on Windows. Do I need to use R version 3?

**Comment by SamGG** [comment]
I am working on with R3.5.1 which is very stable. I can't image myself working with R < 3.0. My advice is to update R, Rtools and Bioconductor.
